services:
  api:
    container_name: wp_api
    build: .
    restart: always
    ports:
      - "${WP_PORT}:80"
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASS}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_DEBUG: 1
      WORDPRESS_SMTP_HOST: ${MAIL_HOST}
      WORDPRESS_SMTP_PORT: ${MAIL_PORT}
      WORDPRESS_SMTP_USERNAME: ${MAIL_USER}
      WORDPRESS_SMTP_PASSWORD: ${MAIL_PASS}
      WORDPRESS_SMTP_FROM_ADDRESS: ${MAIL_USER}
      WORDPRESS_SMTP_FROM_NAME: ${MAIL_NAME}
    volumes:
      - ./plugins:/var/www/html/wp/wp-content/plugins
      - ./themes:/var/www/html/wp/wp-content/themes
    depends_on: 
      - db
  nginx:
    container_name: wp_nginx
    build: 
      context: .
      dockerfile: ./web/Dockerfile
    restart: always
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - api
  db:
    container_name: wp_db
    image: mysql:8.0.2
    restart: always
    ports: 
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - ./data/db:/var/lib/mysql:rw